overthebox: re-indent all the files (#312)

diff --git a/overthebox/files/etc/init.d/otb-remote b/overthebox/files/etc/init.d/otb-remote
--- a/overthebox/files/etc/init.d/otb-remote
+++ b/overthebox/files/etc/init.d/otb-remote
@@ -1,4 +1,5 @@
 #!/bin/sh /etc/rc.common
+# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
 
 START=90
 STOP=90
@@ -30,19 +31,19 @@ mount_ram() {
 }
 
 mount_ssh_dir() {
-    mkdir /tmp/dropbear /tmp/root_ssh
-    if [ ! -d /root/.ssh ]; then
-        mkdir /root/.ssh
-        chmod 700 /root/.ssh
-    fi
-    if [ ! -f "$knownhosts" ]; then
-        touch "$knownhosts"
-    fi
+	mkdir /tmp/dropbear /tmp/root_ssh
+	if [ ! -d /root/.ssh ]; then
+		mkdir /root/.ssh
+		chmod 700 /root/.ssh
+	fi
+	if [ ! -f "$knownhosts" ]; then
+		touch "$knownhosts"
+	fi
 
-    mount_ram /etc/dropbear /tmp/dropbear
-    mount_ram /root/.ssh /tmp/root_ssh
+	mount_ram /etc/dropbear /tmp/dropbear
+	mount_ram /root/.ssh /tmp/root_ssh
 
-    cp $sshkeypriv $sshkey
+	cp $sshkeypriv $sshkey
 }
 
 umount_ram() {
@@ -55,7 +56,7 @@ umount_ram() {
 }
 
 validate_section() {
-        uci_validate_section overthebox remote "${1}" \
+	uci_validate_section overthebox remote "${1}" \
 		'enable:bool:1'            \
 		'ip:string'                \
 		'port:uinteger'            \
@@ -65,69 +66,69 @@ validate_section() {
 }
 
 add_remote_public_key() {
-    if [  -f $authkeys ]; then
-        # Add LF if last character is not LF
-        last=$(tail -c 1 $authkeys)
-        if [ "$last" != "" ]; then
-            echo >> $authkeys
-        fi
-    fi
-    echo "$remote_public_key" >> $authkeys
+	if [  -f $authkeys ]; then
+		# Add LF if last character is not LF
+		last=$(tail -c 1 $authkeys)
+		if [ "$last" != "" ]; then
+			echo >> $authkeys
+		fi
+	fi
+	echo "$remote_public_key" >> $authkeys
 }
 
 start_instance() {
-    local s="${1}"
-    validate_section "${1}" || {
-    	echo "validation failed"
-    	return 1
-    }
+	local s="${1}"
+	validate_section "${1}" || {
+		echo "validation failed"
+		return 1
+	}
 
-    [ "$enable" = "0" ] && return
+	[ "$enable" = "0" ] && return
 
-    [ -n "$ip" ]   || return 1
-    [ -n "$port" ] || return 1
-    [ -n "$forwarded_port" ] || return 1
-    [ -n "$server_public_key" ] || return 1
+	[ -n "$ip" ]   || return 1
+	[ -n "$port" ] || return 1
+	[ -n "$forwarded_port" ] || return 1
+	[ -n "$server_public_key" ] || return 1
 
-    internal_lan_ip=$(uci get -q network.lan.ipaddr) || return
+	internal_lan_ip=$(uci get -q network.lan.ipaddr) || return
 
-    grep -q -s /etc/dropbear /proc/mounts || mount_ssh_dir
-    [ ! -e "$sshkey" ] && return
+	grep -q -s /etc/dropbear /proc/mounts || mount_ssh_dir
+	[ ! -e "$sshkey" ] && return
 
-    # We check if we need to add the key to the authorized keys file
-    if [ -n "$remote_public_key" ]; then
-        # If the file doesn't exist, add the key
-        if [ ! -f $authkeys ]; then
-            add_remote_public_key
-        # If the file exists, but the key is not in it, add it
-        elif ! grep -q "$remote_public_key" $authkeys; then
-            add_remote_public_key
-        fi
-    fi
+	# We check if we need to add the key to the authorized keys file
+	if [ -n "$remote_public_key" ]; then
+		# If the file doesn't exist, add the key
+		if [ ! -f $authkeys ]; then
+			add_remote_public_key
+			# If the file exists, but the key is not in it, add it
+		elif ! grep -q "$remote_public_key" $authkeys; then
+			add_remote_public_key
+		fi
+	fi
 
-    hostkey="$ip $(echo $server_public_key| cut -d' ' -f1,2)"
-    grep -q "$hostkey" $knownhosts || echo "$hostkey" >> $knownhosts
+	hostkey="$ip $(echo $server_public_key| cut -d' ' -f1,2)"
+	grep -q "$hostkey" $knownhosts || echo "$hostkey" >> $knownhosts
 
-    echo run tunnel ssh to $ip:$port $s
+	echo run tunnel ssh to $ip:$port $s
 
-    procd_open_instance
-    procd_set_param env HOME=/root
-    procd_set_param command /usr/bin/ssh -l limited-user $ip -p $port -N -R 6666:$internal_lan_ip:$forwarded_port -i $sshkey -K 30
-    procd_set_param respawn
-    procd_close_instance
+	procd_open_instance
+	procd_set_param env HOME=/root
+	procd_set_param command /usr/bin/ssh -l limited-user $ip -p $port -N -R 6666:$internal_lan_ip:$forwarded_port -i $sshkey -K 30
+	procd_set_param respawn
+	procd_close_instance
 }
 
 start_service() {
-    # do not start ssh tunnel if customer does not want it.
-    [ "$(uci get -q overthebox.me.forbidremote)" = "1" ] && return
+	# do not start ssh tunnel if customer does not want it.
+	[ "$(uci get -q overthebox.me.forbidremote)" = "1" ] && return
 
-    config_load 'overthebox'
-    config_foreach start_instance 'remote'
+	config_load 'overthebox'
+	config_foreach start_instance 'remote'
 }
 
 
 
 stop_service() {
-     umount_ram /etc/dropbear /tmp/dropbear
-     umount_ram /root/.ssh /tmp/root_ssh
+	umount_ram /etc/dropbear /tmp/dropbear
+	umount_ram /root/.ssh /tmp/root_ssh
 }
