Enhance shadowsocks.init robustness (#283)
* Put each local net in a separated line
* Add EXTRA_HELP to describe ifup and ifdown actions
* Use "." instead of "source" to increase compat
* Fix spelling mistakes
* Remove reliability up down count param for tracker
* Embed iptables/ipset hierarchy documentation
* Validate shadowsocks uci configuration
* Update overthebox_test_download_proof script
* Ask ss-redir to reload when mwan3 conf has changed
* Count CPU cores instead of threads
* Don't crash when reload is called if I'm stopped
* Don't use which to find iptables path
* Don't crash on ifup/ifdown when we are stopped
* Only count CPU cores number and not threads number
* Make ifup/ifdown idempotent :)
* Use awk script to find CPU cores number
* Do not export service_running anymore
* Call cleanup in download_proof even without signal
* Launch shadowsocks before setting up ipt rules
* Change DSCP to CS7 for tracker
* Fix indentation issue in overthebox.lua
(cherry picked from commit fc855f5465507a8bdb177207cbdccf8056905c89)

diff --git a/overthebox/files/sbin/overthebox_test_download_proof b/overthebox/files/sbin/overthebox_test_download_proof
--- a/overthebox/files/sbin/overthebox_test_download_proof
+++ b/overthebox/files/sbin/overthebox_test_download_proof
@@ -1,11 +1,29 @@
 #!/bin/sh
+IPT="iptables -w -t nat"
+HOST="proof.ovh.net"
+COMMENT="Test download proof"
 
-iptables -t nat -A OUTPUT -p tcp -d 188.165.12.106 -j SOCKS
+# This function checks existence of an iptables chain
+# $1 is the chain to test
+_chain_exists() {
+    $IPT -nL $1 &> /dev/null
+    return $?
+}
 
-wget http://proof.ovh.net/files/10Gio.dat -O /dev/null &
-WPID=$!
-trap "kill $WPID" SIGINT SIGTERM
-wait $WPID
+# This function is called if we get a SIGINT or SIGTERM
+_cleanup() {
+    $IPT -D socks_emitted_by_myself -d $HOST -j socks_redir -m comment --comment "$COMMENT"
+    echo "Stopped"
+}
 
-echo stopped
-iptables -t nat -D OUTPUT -p tcp -d 188.165.12.106 -j SOCKS
+if ! _chain_exists "socks_emitted_by_myself" || ! _chain_exists "socks_redir"; then
+    echo "Couldn't find the iptables chain to plug myself into. Is ss-redir running?"
+    return 1
+fi
+
+echo "Starting..."
+$IPT -A socks_emitted_by_myself -d $HOST -j socks_redir -m comment --comment "$COMMENT"
+
+trap _cleanup SIGINT SIGTERM
+wget http://$HOST/files/10Gio.dat -O /dev/null
+_cleanup
