otb-dscp: refactor init

diff --git a/otb-dscp/init b/otb-dscp/init
--- a/otb-dscp/init
+++ b/otb-dscp/init
@@ -1,83 +1,111 @@
 #!/bin/sh /etc/rc.common
 # vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
 
+# shellcheck disable=SC2034
 START=60
 
-COMMID="$(date +%s)_$$"
-IPT="iptables -t mangle -w"
+# shellcheck disable=SC1091
+. /lib/functions.sh
 
-# Generate dscp tagging preferences
-_setup_dscp() {
-	local proto ipset src_ip src_port dest dest_ip dest_port class direction
+config_load dscp
 
-	config_get proto "$1" proto "all"
-	config_get ipset "$1" ipset
-	config_get src_ip "$1" src_ip "0.0.0.0/0"
-	config_get src_port "$1" src_port "0:65535"
-	config_get dest_ip "$1" dest_ip "0.0.0.0/0"
-	config_get dest_port "$1" dest_port "0:65535"
+_add_dscp_rules() {
+	proto=
+	src_ip=
+	src_port=
+	dest_ip=
+	dest_port=
+	class=
+	direction=
+	comment=
+
+	config_get proto "$1" proto all
+	config_get src_ip "$1" src_ip 0.0.0.0/0
+	config_get src_port "$1" src_port 0:65535
+	config_get dest_ip "$1" dest_ip 0.0.0.0/0
+	config_get dest_port "$1" dest_port 0:65535
 	config_get class "$1" class
 	config_get direction "$1" direction "upload"
+	config_get comment "$1" comment "-"
 
-	# Take OTB point of view when using both direction (inverse source and destination)
+	[ "$direction" = "upload" ] || [ "$direction" = "both" ] || return
+
+	_multport_option() {
+		src_port=$1
+		dest_port=$2
+		# shellcheck disable=SC2039
+		echo "-m multiport --sports $src_port -m multiport --dports $dest_port"
+	}
+
+	multiport=false
+	multiport_config=
+	case $proto in
+		tcp|udp)
+			multiport=true
+			;;
+		*);;
+	esac
+
+	# Add upload rules
+	[ "$multiport" = "true" ] && multiport_config=$(_multport_option "$src_port" "$dest_port")
+	# shellcheck disable=SC2086
+	iptables -w -t mangle -A dscp -p "$proto" -s "$src_ip" -d "$dest_ip" $multiport_config -m comment --comment "$comment" -j DSCP --set-dscp-class "$class"
+	# shellcheck disable=SC2086
+	iptables -w -t mangle -A dscp -p "$proto" -s "$src_ip" -d "$dest_ip" $multiport_config -m comment --comment "$comment" -j RETURN
+
+	# Add download rules
 	if [ "$direction" = "both" ]; then
-		config_get src_ip "$1" dest_ip "0.0.0.0/0"
-		config_get src_port "$1" dest_port "0:65535"
-		config_get dest_ip "$1" src_ip "0.0.0.0/0"
-		config_get dest_port "$1" src_port "0:65535"
-	fi
-
-	dest=${dest_ip:-$ipset}
-
-	if [ "$direction" = "upload" ] || [ "$direction" = "both" ]; then
-		case $proto in
-			udp|tcp)
-				$IPT -A dscp -p "$proto" -s "$src_ip" -d "$dest" -m multiport --sports "$src_port" -m multiport --dports "$dest_port" -m comment --comment "dscp_$COMMID" -j DSCP --set-dscp-class "$class"
-				$IPT -A dscp -p "$proto" -s "$src_ip" -d "$dest" -m multiport --sports "$src_port" -m multiport --dports "$dest_port" -m comment --comment "dscp_$COMMID" -j RETURN
-				;;
-			*)
-				$IPT -A dscp -p "$proto" -s "$src_ip" -d "$dest" -m comment --comment "dscp_$COMMID" -j DSCP --set-dscp-class "$class"
-				$IPT -A dscp -p "$proto" -s "$src_ip" -d "$dest" -m comment --comment "dscp_$COMMID" -j RETURN
-				;;
-		esac
+		[ "$multiport" = "true" ] && multiport_config=$(_multport_option "$dest_port" "$src_port")
+		# shellcheck disable=SC2086
+		iptables -w -t mangle -A dscp -p "$proto" -s "$dest_ip" -d "$src_ip" $multiport_config -m comment --comment "$comment" -j DSCP --set-dscp-class "$class"
+		# shellcheck disable=SC2086
+		iptables -w -t mangle -A dscp -p "$proto" -s "$dest_ip" -d "$src_ip" $multiport_config -m comment --comment "$comment" -j RETURN
 	fi
 }
 
-reload() {
-	config_load dscp
-	config_foreach _setup_dscp classify
-
-	iptables-save | grep "A dscp" | grep "dscp_" | grep -v "dscp_$COMMID" | sed "s/-A/\/usr\/sbin\/iptables -t mangle -w -D/g" | sh
-
-#	if [ "$1" != "tun0" ]; then
-#		/usr/bin/pkill -USR2 -f "mwan3track -i tun0"
-#	fi
+_add_static_length_rule() {
+	length=$1
+	class=$2
+	iptables -t mangle -A dscp -p tcp -m length --length "$length" -j DSCP --set-dscp-class "$class"
+	iptables -t mangle -A dscp -p tcp -m length --length "$length" -j RETURN
 }
 
-restart() {
-	stop
-	restart
+_add_static_length_rules() {
+	# Interactive traffic
+	_add_static_length_rule :89 cs3
+	# Light traffic
+	_add_static_length_rule 90:511 cs2
+	# Heavy traffic
+	_add_static_length_rule 512: cs1
 }
 
-_setup_dscp_tcp() {
-	$IPT -A dscp -p tcp -m length --length "$1" -m comment --comment "dscp" -j DSCP --set-dscp-class "$2"
-	$IPT -A dscp -p tcp -m length --length "$1" -m comment --comment "dscp" -j RETURN
+_remove_dscp_chain() {
+	iptables -w -t mangle -F dscp 2>/dev/null || return
+	iptables -w -t mangle -D PREROUTING -j dscp
+	iptables -w -t mangle -X dscp
 }
 
-start() {
-	$IPT -D PREROUTING -j dscp 2>/dev/null
-	$IPT -I PREROUTING -j dscp
-
-	_setup_dscp_tcp ":89"    "cs3"  # Interactive
-	_setup_dscp_tcp "90:511" "cs2"  # Light
-	_setup_dscp_tcp "512:"   "cs1"  # Heavy
-
-	reload
+_add_dscp_chain() {
+	iptables -w -t mangle -N dscp
+	iptables -w -t mangle -A PREROUTING -j dscp
 }
 
-stop() {
-	$IPT -F dscp 2>/dev/null
-	$IPT -N dscp 2>/dev/null
+start()
+{
+	# Cleanup
+	_remove_dscp_chain
+	_add_dscp_chain
+
+	# Add rules base on the user configuration
+	config_foreach _add_dscp_rules classify
+
+	# Add rules based on the length of the packets
+	_add_static_length_rules
+}
+
+stop()
+{
+	_remove_dscp_chain
 }
 
 service_triggers() {
