otb-remote: Cleanup and small fixes
Signed-off-by: Adrien Gallouët <adrien@gallouet.fr>

diff --git a/otb-remote/otb-action-remoteAccessDisconnect b/otb-remote/otb-action-remoteAccessDisconnect
--- a/otb-remote/otb-action-remoteAccessDisconnect
+++ b/otb-remote/otb-action-remoteAccessDisconnect
@@ -3,20 +3,39 @@
 
 set -e
 
+[ "$1" ]
+
 # shellcheck disable=SC1091
 . /lib/overthebox
 
-remote_access_id="$(otb_json_get "$1" 'arguments.remote_access_id')"
+content="$1"
+
+_get() {
+	otb_json_get "$content" "arguments.$1"
+}
+
+remote_access_id="$(_get remote_access_id)"
+
+if [ -z "$remote_access_id" ] || [ "$remote_access_id" = "null" ]; then
+	echo "Invalid remote access ID"
+	exit 1
+fi
+
+otb_debug "Disconnect remote access $remote_access_id"
+
 uci_id=$(echo "$remote_access_id" | tr - _)
+luci_user=$(uci -q get "otb-remote.$uci_id.luci_user" || true)
 
-[ -e /etc/dropbear/authorized_keys ] && \
-	sed -i "/$uci_id/d" /etc/dropbear/authorized_keys
+if [ -w /etc/dropbear/authorized_keys ]; then
+	sed -i "/$uci_id/d" /etc/dropbear/authorized_keys || true
+fi
 
-luci_user=$(uci -q get otb-remote."${uci_id}".luci_user) || true
-[ -n "$luci_user" ] && deluser "$luci_user"
+if [ "$luci_user" ]; then
+	deluser "$luci_user" || true
+fi
 
 uci -q batch <<EOF
-delete otb-remote.${uci_id}
+delete otb-remote.$uci_id
 commit otb-remote
 EOF
 
