simpletracker: Remove extra spaces and tabulate
Signed-off-by: Kevin Lanvin <kevin.lanvin@corp.ovh.com>

diff --git a/simpletracker/files/etc/init.d/simpletracker b/simpletracker/files/etc/init.d/simpletracker
--- a/simpletracker/files/etc/init.d/simpletracker
+++ b/simpletracker/files/etc/init.d/simpletracker
@@ -1,4 +1,5 @@
 #!/bin/sh /etc/rc.common
+# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
 START=90
 STOP=10
 
@@ -14,17 +15,17 @@ validate_section() {
 
 
 start_track_interface() {
-	validate_section "$1" || { 
-		echo "Cannot read uci configuration"
-		return
-	}
+	validate_section "$1" || {
+	echo "Cannot read uci configuration"
+	return
+}
 
-	procd_open_instance
-	procd_set_param command /usr/bin/track_interface.sh -m "$method" -d "tracker.overthebox.ovh" -t "$timeout" -h "$host" "$interface"
-	procd_set_param respawn  0 3 0
-	procd_set_param stdout 1
-	procd_set_param user root
-	procd_close_instance
+procd_open_instance
+procd_set_param command /usr/bin/track_interface.sh -m "$method" -d "tracker.overthebox.ovh" -t "$timeout" -h "$host" "$interface"
+procd_set_param respawn  0 3 0
+procd_set_param stdout 1
+procd_set_param user root
+procd_close_instance
 }
 
 
